import 'content_lib.dart';

void main() {
  ensureSection(
    id: 'sec_a2',
    level: 'A2',
    title: const Tr('Niveau A2 — sich verständigen', 'Level A2 — getting by', 'Nivå A2 — att göra sig förstådd', 'Niveau A2 — je verstaanbaar maken'),
  );

  writeUnit(UnitSpec(
    id: 'unit_verben_alltag',
    sectionId: 'sec_a2',
    level: 'A2',
    topic: 'verbs',
    title: const Tr('Verben im Alltag', 'Everyday verbs', 'Vardagliga verb', 'Alledaagse werkwoorden'),
    lexemes: [
      LexemeSpec(id: 'lex_v_gehen', am: 'መሄድ', tr: 'mehed', pos: 'verb', topic: 'verbs', level: 'A2', verified: true, t: const Tr('gehen', 'to go', 'gå', 'gaan')),
      LexemeSpec(id: 'lex_v_kommen', am: 'መምጣት', tr: 'memt\'at', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('kommen', 'to come', 'komma', 'komen')),
      LexemeSpec(id: 'lex_v_sehen', am: 'ማየት', tr: 'mayet', pos: 'verb', topic: 'verbs', level: 'A2', verified: true, t: const Tr('sehen', 'to see', 'se', 'zien')),
      LexemeSpec(id: 'lex_v_machen', am: 'ማድረግ', tr: 'madirege', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('machen, tun', 'to do, to make', 'göra', 'doen, maken')),
      LexemeSpec(id: 'lex_v_geben', am: 'መስጠት', tr: "meset'", pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('geben', 'to give', 'ge', 'geven')),
      LexemeSpec(id: 'lex_v_nehmen', am: 'መውሰድ', tr: 'mewsed', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('nehmen', 'to take', 'ta', 'nemen')),
      LexemeSpec(id: 'lex_v_wollen', am: 'መፈለግ', tr: 'mefeleg', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('wollen', 'to want', 'vilja', 'willen')),
      LexemeSpec(id: 'lex_v_koennen', am: 'መቻል', tr: 'mechal', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('können', 'to be able to, can', 'kunna', 'kunnen')),
      LexemeSpec(id: 'lex_v_wissen', am: 'ማወቅ', tr: "mawek'", pos: 'verb', topic: 'verbs', level: 'A2', verified: true, t: const Tr('wissen', 'to know', 'veta', 'weten')),
      LexemeSpec(id: 'lex_v_sprechen', am: 'መናገር', tr: 'menager', pos: 'verb', topic: 'verbs', level: 'A2', verified: true, t: const Tr('sprechen, reden', 'to speak', 'tala', 'spreken')),
      LexemeSpec(id: 'lex_v_lieben', am: 'መውደድ', tr: 'mewded', pos: 'verb', topic: 'verbs', level: 'A2', verified: true, t: const Tr('lieben, mögen', 'to love, to like', 'älska, tycka om', 'liefhebben, leuk vinden')),
      LexemeSpec(id: 'lex_v_arbeiten', am: 'መስራት', tr: 'mesrat', pos: 'verb', topic: 'verbs', level: 'A2', verified: true, t: const Tr('arbeiten', 'to work', 'arbeta', 'werken')),
      LexemeSpec(id: 'lex_v_lernen', am: 'መማር', tr: 'memar', pos: 'verb', topic: 'verbs', level: 'A2', verified: true, t: const Tr('lernen', 'to learn', 'lära sig', 'leren')),
      LexemeSpec(id: 'lex_v_schlafen', am: 'መተኛት', tr: 'metegnat', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('schlafen', 'to sleep', 'sova', 'slapen')),
      LexemeSpec(id: 'lex_v_spielen', am: 'መጫወት', tr: 'mechawet', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('spielen', 'to play', 'leka, spela', 'spelen')),
      LexemeSpec(id: 'lex_v_laufen', am: 'መሮጥ', tr: "meroth'", pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('laufen, rennen', 'to run', 'springa', 'rennen')),
      LexemeSpec(id: 'lex_v_sitzen', am: 'መቀመጥ', tr: "mek'emet'", pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('sitzen', 'to sit', 'sitta', 'zitten')),
      LexemeSpec(id: 'lex_v_stehen', am: 'መቆም', tr: "mek'om", pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('stehen', 'to stand', 'stå', 'staan')),
      LexemeSpec(id: 'lex_v_oeffnen', am: 'መክፈት', tr: 'mekfet', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('öffnen', 'to open', 'öppna', 'openen')),
      LexemeSpec(id: 'lex_v_schliessen', am: 'መዝጋት', tr: 'mezgat', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('schließen', 'to close', 'stänga', 'sluiten')),
      LexemeSpec(id: 'lex_v_helfen', am: 'መርዳት', tr: 'merdat', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('helfen', 'to help', 'hjälpa', 'helpen')),
      LexemeSpec(id: 'lex_v_fragen', am: 'መጠየቅ', tr: "met'eyek'", pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('fragen', 'to ask', 'fråga', 'vragen')),
      LexemeSpec(id: 'lex_v_antworten', am: 'መመለስ', tr: 'memeles', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('antworten', 'to answer', 'svara', 'antwoorden')),
      LexemeSpec(id: 'lex_v_denken', am: 'ማሰብ', tr: 'maseb', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('denken', 'to think', 'tänka', 'denken')),
      LexemeSpec(id: 'lex_v_verstehen', am: 'መረዳት', tr: 'meredat', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('verstehen', 'to understand', 'förstå', 'begrijpen')),
      LexemeSpec(id: 'lex_v_hoeren', am: 'መስማት', tr: 'mesmat', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('hören', 'to hear', 'höra', 'horen')),
      LexemeSpec(id: 'lex_v_kochen', am: 'ማብሰል', tr: 'mabsel', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('kochen', 'to cook', 'laga mat', 'koken')),
      LexemeSpec(id: 'lex_v_waschen', am: 'ማጠብ', tr: "mat'eb", pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('waschen', 'to wash', 'tvätta', 'wassen')),
      LexemeSpec(id: 'lex_v_warten', am: 'መጠበቅ', tr: "met'ebek'", pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('warten', 'to wait', 'vänta', 'wachten')),
      LexemeSpec(id: 'lex_v_suchen', am: 'መፍለግ', tr: 'meflege', pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('suchen', 'to search', 'söka', 'zoeken')),
      LexemeSpec(id: 'lex_v_bringen', am: 'ማምጣት', tr: "mamt'at", pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('bringen', 'to bring', 'ta med', 'brengen')),
      LexemeSpec(id: 'lex_v_lachen', am: 'መሳቅ', tr: "mesak'", pos: 'verb', topic: 'verbs', level: 'A2', t: const Tr('lachen', 'to laugh', 'skratta', 'lachen')),
    ],
    sentences: [
      SentenceSpec(id: 'sen_wuha_meweded', am: 'ውሃ መጠጣት እወዳለሁ።', tr: "wuha met'et'at iwedalehu.", level: 'A2', uses: ['lex_wasser', 'lex_v_lieben'], chunks: ['wuha', "met'et'at", 'iwedalehu'], t: const Tr('Ich mag es, Wasser zu trinken.', 'I like drinking water.', 'Jag tycker om att dricka vatten.', 'Ik houd van water drinken.'), verified: false),
      SentenceSpec(id: 'sen_ine_ihedalehu', am: 'እኔ ወደ ቤት እሄዳለሁ።', tr: 'ine wede biet ihedalehu.', level: 'A2', uses: ['lex_ine', 'lex_haus', 'lex_v_gehen'], chunks: ['ine', 'wede', 'biet', 'ihedalehu'], t: const Tr('Ich gehe nach Hause.', 'I am going home.', 'Jag går hem.', 'Ik ga naar huis.'), verified: false),
    ],
  ));

  writeUnit(UnitSpec(
    id: 'unit_gegenwart_vergangenheit',
    sectionId: 'sec_a2',
    level: 'A2',
    topic: 'grammar_time',
    title: const Tr('Gegenwart & Vergangenheit', 'Present & past', 'Nutid & dåtid', 'Heden & verleden'),
    lexemes: [
      LexemeSpec(id: 'lex_ich_gehe', am: 'እሄዳለሁ', tr: 'ihedalehu', pos: 'phrase', topic: 'grammar_time', level: 'A2', t: const Tr('ich gehe', 'I go', 'jag går', 'ik ga')),
      LexemeSpec(id: 'lex_ich_ging', am: 'ሄድኩ', tr: 'hedku', pos: 'phrase', topic: 'grammar_time', level: 'A2', t: const Tr('ich ging', 'I went', 'jag gick', 'ik ging')),
      LexemeSpec(id: 'lex_ich_ass', am: 'በላሁ', tr: 'belahu', pos: 'phrase', topic: 'grammar_time', level: 'A2', t: const Tr('ich aß', 'I ate', 'jag åt', 'ik at')),
      LexemeSpec(id: 'lex_ich_trank', am: 'ጠጣሁ', tr: "t'et'ahu", pos: 'phrase', topic: 'grammar_time', level: 'A2', t: const Tr('ich trank', 'I drank', 'jag drack', 'ik dronk')),
      LexemeSpec(id: 'lex_jetzt', am: 'አሁን', tr: 'ahun', pos: 'adverb', topic: 'grammar_time', level: 'A2', verified: true, t: const Tr('jetzt', 'now', 'nu', 'nu')),
      LexemeSpec(id: 'lex_frueher', am: 'ከዚህ በፊት', tr: 'kezih befit', pos: 'adverb', topic: 'grammar_time', level: 'A2', t: const Tr('früher, vorher', 'before, in the past', 'tidigare, förut', 'vroeger')),
      LexemeSpec(id: 'lex_schon', am: 'ቀድሞ', tr: 'kedmo', pos: 'adverb', topic: 'grammar_time', level: 'A2', t: const Tr('schon, bereits', 'already', 'redan', 'al')),
      LexemeSpec(id: 'lex_immer', am: 'ሁልጊዜ', tr: 'hulgize', pos: 'adverb', topic: 'grammar_time', level: 'A2', t: const Tr('immer', 'always', 'alltid', 'altijd')),
      LexemeSpec(id: 'lex_manchmal', am: 'አልፎ አልፎ', tr: 'alfo alfo', pos: 'adverb', topic: 'grammar_time', level: 'A2', t: const Tr('manchmal', 'sometimes', 'ibland', 'soms')),
      LexemeSpec(id: 'lex_nie', am: 'በፍጹም', tr: 'befitsum', pos: 'adverb', topic: 'grammar_time', level: 'A2', t: const Tr('nie, niemals', 'never', 'aldrig', 'nooit')),
      LexemeSpec(id: 'lex_bald', am: 'በቅርቡ', tr: 'bekiribu', pos: 'adverb', topic: 'grammar_time', level: 'A2', t: const Tr('bald', 'soon', 'snart', 'binnenkort')),
      LexemeSpec(id: 'lex_spaet', am: 'ዘግይቶ', tr: 'zegiyto', pos: 'adverb', topic: 'grammar_time', level: 'A2', t: const Tr('spät', 'late', 'sent', 'laat')),
    ],
    sentences: [
      SentenceSpec(id: 'sen_ahun_ihedalehu', am: 'እኔ አሁን እሄዳለሁ።', tr: 'ine ahun ihedalehu.', level: 'A2', uses: ['lex_ine', 'lex_jetzt', 'lex_ich_gehe'], chunks: ['ine', 'ahun', 'ihedalehu'], t: const Tr('Ich gehe jetzt.', 'I am going now.', 'Jag går nu.', 'Ik ga nu.'), verified: false),
    ],
  ));

  writeUnit(UnitSpec(
    id: 'unit_koerper_gesundheit',
    sectionId: 'sec_a2',
    level: 'A2',
    topic: 'body_health',
    title: const Tr('Körper & Gesundheit', 'Body & health', 'Kropp & hälsa', 'Lichaam & gezondheid'),
    lexemes: [
      LexemeSpec(id: 'lex_kopf', am: 'ራስ', tr: 'ras', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '🗣️', verified: true, t: const Tr('der Kopf', 'head', 'huvud', 'hoofd')),
      LexemeSpec(id: 'lex_auge', am: 'ዓይን', tr: 'ayn', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '👁️', verified: true, t: const Tr('das Auge', 'eye', 'öga', 'oog')),
      LexemeSpec(id: 'lex_ohr', am: 'ጆሮ', tr: 'joro', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '👂', verified: true, t: const Tr('das Ohr', 'ear', 'öra', 'oor')),
      LexemeSpec(id: 'lex_nase', am: 'አፍንጫ', tr: 'afincha', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '👃', verified: true, t: const Tr('die Nase', 'nose', 'näsa', 'neus')),
      LexemeSpec(id: 'lex_mund', am: 'አፍ', tr: 'af', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '👄', verified: true, t: const Tr('der Mund', 'mouth', 'mun', 'mond')),
      LexemeSpec(id: 'lex_hand', am: 'እጅ', tr: 'ij', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '✋', verified: true, t: const Tr('die Hand', 'hand', 'hand', 'hand')),
      LexemeSpec(id: 'lex_fuss', am: 'እግር', tr: 'igir', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '🦵', verified: true, t: const Tr('der Fuß, das Bein', 'foot, leg', 'fot, ben', 'voet, been')),
      LexemeSpec(id: 'lex_bauch', am: 'ሆድ', tr: 'hod', pos: 'noun', topic: 'body_health', level: 'A2', verified: true, t: const Tr('der Bauch', 'belly, stomach', 'mage', 'buik')),
      LexemeSpec(id: 'lex_herz', am: 'ልብ', tr: 'lib', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '❤️', verified: true, t: const Tr('das Herz', 'heart', 'hjärta', 'hart')),
      LexemeSpec(id: 'lex_zahn', am: 'ጥርስ', tr: "t'iris", pos: 'noun', topic: 'body_health', level: 'A2', emoji: '🦷', t: const Tr('der Zahn', 'tooth', 'tand', 'tand')),
      LexemeSpec(id: 'lex_haar', am: 'ፀጉር', tr: "ts'egur", pos: 'noun', topic: 'body_health', level: 'A2', t: const Tr('das Haar', 'hair', 'hår', 'haar')),
      LexemeSpec(id: 'lex_schmerz', am: 'ህመም', tr: 'himem', pos: 'noun', topic: 'body_health', level: 'A2', verified: true, t: const Tr('der Schmerz', 'pain', 'smärta', 'pijn')),
      LexemeSpec(id: 'lex_arzt', am: 'ሐኪም', tr: 'hakim', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '👨‍⚕️', verified: true, t: const Tr('der Arzt, die Ärztin', 'doctor', 'läkare', 'dokter')),
      LexemeSpec(id: 'lex_medikament', am: 'መድሃኒት', tr: 'medhanit', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '💊', verified: true, t: const Tr('das Medikament', 'medicine', 'medicin', 'medicijn')),
      LexemeSpec(id: 'lex_krank_phrase', am: 'ታምሜያለሁ', tr: 'tammeyalehu', pos: 'phrase', topic: 'body_health', level: 'A2', t: const Tr('Ich bin krank', 'I am sick', 'Jag är sjuk', 'Ik ben ziek')),
      LexemeSpec(id: 'lex_gesund', am: 'ጤናማ', tr: "t'enama", pos: 'adjective', topic: 'body_health', level: 'A2', t: const Tr('gesund', 'healthy', 'frisk', 'gezond')),
      LexemeSpec(id: 'lex_geht_nicht_gut', am: 'ደህና አይደለሁም', tr: 'dehna aydelehum', pos: 'phrase', topic: 'body_health', level: 'A2', t: const Tr('Mir geht es nicht gut', "I'm not well", 'Jag mår inte bra', 'Het gaat niet goed met mij')),
      LexemeSpec(id: 'lex_schulter', am: 'ትከሻ', tr: 'tikesha', pos: 'noun', topic: 'body_health', level: 'A2', t: const Tr('die Schulter', 'shoulder', 'axel', 'schouder')),
      LexemeSpec(id: 'lex_ruecken', am: 'ጀርባ', tr: 'jerba', pos: 'noun', topic: 'body_health', level: 'A2', t: const Tr('der Rücken', 'back', 'rygg', 'rug')),
      LexemeSpec(id: 'lex_knie', am: 'ጉልበት', tr: 'gulbet', pos: 'noun', topic: 'body_health', level: 'A2', t: const Tr('das Knie', 'knee', 'knä', 'knie')),
      LexemeSpec(id: 'lex_finger', am: 'ጣት', tr: "t'at", pos: 'noun', topic: 'body_health', level: 'A2', t: const Tr('der Finger', 'finger', 'finger', 'vinger')),
      LexemeSpec(id: 'lex_hals', am: 'አንገት', tr: 'anget', pos: 'noun', topic: 'body_health', level: 'A2', t: const Tr('der Hals', 'neck', 'hals', 'nek')),
      LexemeSpec(id: 'lex_haut', am: 'ቆዳ', tr: "k'oda", pos: 'noun', topic: 'body_health', level: 'A2', t: const Tr('die Haut', 'skin', 'hud', 'huid')),
      LexemeSpec(id: 'lex_fieber', am: 'ትኩሳት', tr: 'tikusat', pos: 'noun', topic: 'body_health', level: 'A2', t: const Tr('das Fieber', 'fever', 'feber', 'koorts')),
      LexemeSpec(id: 'lex_husten', am: 'ሳል', tr: 'sal', pos: 'noun', topic: 'body_health', level: 'A2', t: const Tr('der Husten', 'cough', 'hosta', 'hoest')),
      LexemeSpec(id: 'lex_apotheke', am: 'ፋርማሲ', tr: 'farmasi', pos: 'noun', topic: 'body_health', level: 'A2', emoji: '💊', verified: true, t: const Tr('die Apotheke', 'pharmacy', 'apotek', 'apotheek')),
      LexemeSpec(id: 'lex_krankenschwester', am: 'ነርስ', tr: 'ners', pos: 'noun', topic: 'body_health', level: 'A2', verified: true, t: const Tr('die Krankenschwester, der Pfleger', 'nurse', 'sjuksköterska', 'verpleegkundige')),
      LexemeSpec(id: 'lex_gesundheit_noun', am: 'ጤና', tr: "t'ena", pos: 'noun', topic: 'body_health', level: 'A2', verified: true, t: const Tr('die Gesundheit', 'health', 'hälsa', 'gezondheid')),
      LexemeSpec(id: 'lex_muede', am: 'ደክሞኛል', tr: 'dekmogniall', pos: 'phrase', topic: 'body_health', level: 'A2', t: const Tr('Ich bin müde', 'I am tired', 'Jag är trött', 'Ik ben moe')),
    ],
    sentences: [
      SentenceSpec(id: 'sen_rasi_yimenal', am: 'ራሴ ይመናል።', tr: 'rasie yimenal.', level: 'A2', uses: ['lex_kopf'], chunks: ['rasie', 'yimenal'], t: const Tr('Mir tut der Kopf weh.', 'My head hurts.', 'Jag har huvudvärk.', 'Mijn hoofd doet pijn.'), verified: false),
      SentenceSpec(id: 'sen_hakim_negn', am: 'ወደ ሐኪም እሄዳለሁ።', tr: 'wede hakim ihedalehu.', level: 'A2', uses: ['lex_arzt', 'lex_ich_gehe'], chunks: ['wede', 'hakim', 'ihedalehu'], t: const Tr('Ich gehe zum Arzt.', 'I am going to the doctor.', 'Jag går till läkaren.', 'Ik ga naar de dokter.'), verified: false),
    ],
  ));

  writeUnit(UnitSpec(
    id: 'unit_arbeit_schule',
    sectionId: 'sec_a2',
    level: 'A2',
    topic: 'work_school',
    title: const Tr('Arbeit & Schule', 'Work & school', 'Arbete & skola', 'Werk & school'),
    lexemes: [
      LexemeSpec(id: 'lex_beruf', am: 'ስራ', tr: 'sira', pos: 'noun', topic: 'work_school', level: 'A2', emoji: '💼', verified: true, t: const Tr('die Arbeit, der Beruf', 'work, job', 'arbete, jobb', 'werk, baan')),
      LexemeSpec(id: 'lex_buero', am: 'ቢሮ', tr: 'biro', pos: 'noun', topic: 'work_school', level: 'A2', emoji: '🏢', verified: true, t: const Tr('das Büro', 'office', 'kontor', 'kantoor')),
      LexemeSpec(id: 'lex_lehrer', am: 'አስተማሪ', tr: 'astemari', pos: 'noun', topic: 'work_school', level: 'A2', emoji: '👩‍🏫', verified: true, t: const Tr('der Lehrer, die Lehrerin', 'teacher', 'lärare', 'leraar')),
      LexemeSpec(id: 'lex_schueler', am: 'ተማሪ', tr: 'temari', pos: 'noun', topic: 'work_school', level: 'A2', emoji: '🎓', verified: true, t: const Tr('der Schüler, der Student', 'student', 'student', 'student')),
      LexemeSpec(id: 'lex_buch', am: 'መጽሐፍ', tr: "mets'ihaf", pos: 'noun', topic: 'work_school', level: 'A2', emoji: '📖', verified: true, t: const Tr('das Buch', 'book', 'bok', 'boek')),
      LexemeSpec(id: 'lex_v_schreiben', am: 'መፃፍ', tr: "mets'af", pos: 'verb', topic: 'work_school', level: 'A2', t: const Tr('schreiben', 'to write', 'skriva', 'schrijven')),
      LexemeSpec(id: 'lex_v_lesen', am: 'ማንበብ', tr: 'manbeb', pos: 'verb', topic: 'work_school', level: 'A2', verified: true, t: const Tr('lesen', 'to read', 'läsa', 'lezen')),
      LexemeSpec(id: 'lex_stift', am: 'እርሳስ', tr: 'irsas', pos: 'noun', topic: 'work_school', level: 'A2', emoji: '✏️', t: const Tr('der Stift, Bleistift', 'pencil', 'penna', 'potlood')),
      LexemeSpec(id: 'lex_papier', am: 'ወረቀት', tr: 'wereket', pos: 'noun', topic: 'work_school', level: 'A2', emoji: '📄', verified: true, t: const Tr('das Papier', 'paper', 'papper', 'papier')),
      LexemeSpec(id: 'lex_universitaet', am: 'ዩኒቨርሲቲ', tr: 'yuniversiti', pos: 'noun', topic: 'work_school', level: 'A2', emoji: '🎓', verified: true, t: const Tr('die Universität', 'university', 'universitet', 'universiteit')),
      LexemeSpec(id: 'lex_pruefung', am: 'ፈተና', tr: 'fetena', pos: 'noun', topic: 'work_school', level: 'A2', verified: true, t: const Tr('die Prüfung', 'exam, test', 'prov', 'examen')),
      LexemeSpec(id: 'lex_computer', am: 'ኮምፒተር', tr: 'computer', pos: 'noun', topic: 'work_school', level: 'A2', emoji: '💻', verified: true, t: const Tr('der Computer', 'computer', 'dator', 'computer')),
      LexemeSpec(id: 'lex_chef', am: 'አለቃ', tr: 'aleka', pos: 'noun', topic: 'work_school', level: 'A2', t: const Tr('der Chef, die Chefin', 'boss', 'chef', 'baas')),
      LexemeSpec(id: 'lex_gehalt', am: 'ደመወዝ', tr: 'demewez', pos: 'noun', topic: 'work_school', level: 'A2', t: const Tr('das Gehalt', 'salary', 'lön', 'salaris')),
      LexemeSpec(id: 'lex_firma', am: 'ድርጅት', tr: 'dirijit', pos: 'noun', topic: 'work_school', level: 'A2', t: const Tr('die Firma, das Unternehmen', 'company', 'företag', 'bedrijf')),
      LexemeSpec(id: 'lex_hausaufgabe', am: 'የቤት ስራ', tr: 'yebiet sira', pos: 'noun', topic: 'work_school', level: 'A2', t: const Tr('die Hausaufgabe', 'homework', 'läxa', 'huiswerk')),
      LexemeSpec(id: 'lex_tafel', am: 'ሰሌዳ', tr: 'seleda', pos: 'noun', topic: 'work_school', level: 'A2', t: const Tr('die Tafel', 'board', 'tavla', 'schoolbord')),
      LexemeSpec(id: 'lex_tasche', am: 'ቦርሳ', tr: 'borsa', pos: 'noun', topic: 'work_school', level: 'A2', emoji: '🎒', verified: true, t: const Tr('die Tasche', 'bag', 'väska', 'tas')),
      LexemeSpec(id: 'lex_ferien', am: 'እረፍት', tr: 'ireft', pos: 'noun', topic: 'work_school', level: 'A2', t: const Tr('die Ferien, der Urlaub', 'vacation, holiday', 'semester', 'vakantie')),
    ],
    sentences: [
      SentenceSpec(id: 'sen_temari_negn', am: 'እኔ ተማሪ ነኝ።', tr: 'ine temari negn.', level: 'A2', uses: ['lex_ine', 'lex_schueler'], chunks: ['ine', 'temari', 'negn'], t: const Tr('Ich bin Student.', 'I am a student.', 'Jag är student.', 'Ik ben een student.')),
      SentenceSpec(id: 'sen_metsihaf_manbeb', am: 'መጽሐፍ አነባለሁ።', tr: "mets'ihaf anebalehu.", level: 'A2', uses: ['lex_buch', 'lex_v_lesen'], chunks: ["mets'ihaf", 'anebalehu'], t: const Tr('Ich lese ein Buch.', 'I read a book.', 'Jag läser en bok.', 'Ik lees een boek.'), verified: false),
    ],
  ));

  writeUnit(UnitSpec(
    id: 'unit_reisen_verkehr',
    sectionId: 'sec_a2',
    level: 'A2',
    topic: 'travel',
    title: const Tr('Reisen & Verkehr', 'Travel & transport', 'Resor & trafik', 'Reizen & verkeer'),
    lexemes: [
      LexemeSpec(id: 'lex_bus', am: 'አውቶቢስ', tr: 'awtobis', pos: 'noun', topic: 'travel', level: 'A2', emoji: '🚌', verified: true, t: const Tr('der Bus', 'bus', 'buss', 'bus')),
      LexemeSpec(id: 'lex_taxi', am: 'ታክሲ', tr: 'taksi', pos: 'noun', topic: 'travel', level: 'A2', emoji: '🚕', verified: true, t: const Tr('das Taxi', 'taxi', 'taxi', 'taxi')),
      LexemeSpec(id: 'lex_flugzeug', am: 'አውሮፕላን', tr: 'awroplan', pos: 'noun', topic: 'travel', level: 'A2', emoji: '✈️', verified: true, t: const Tr('das Flugzeug', 'airplane', 'flygplan', 'vliegtuig')),
      LexemeSpec(id: 'lex_ticket', am: 'ትኬት', tr: 'tiket', pos: 'noun', topic: 'travel', level: 'A2', emoji: '🎫', verified: true, t: const Tr('das Ticket, die Fahrkarte', 'ticket', 'biljett', 'ticket')),
      LexemeSpec(id: 'lex_gepaeck', am: 'ሻንጣ', tr: 'shanta', pos: 'noun', topic: 'travel', level: 'A2', emoji: '🧳', verified: true, t: const Tr('das Gepäck, die Tasche', 'luggage, bag', 'bagage', 'bagage')),
      LexemeSpec(id: 'lex_auto', am: 'መኪና', tr: 'mekina', pos: 'noun', topic: 'travel', level: 'A2', emoji: '🚗', verified: true, t: const Tr('das Auto', 'car', 'bil', 'auto')),
      LexemeSpec(id: 'lex_zug', am: 'ባቡር', tr: 'babur', pos: 'noun', topic: 'travel', level: 'A2', emoji: '🚆', verified: true, t: const Tr('der Zug', 'train', 'tåg', 'trein')),
      LexemeSpec(id: 'lex_v_fahren', am: 'መንዳት', tr: 'mendat', pos: 'verb', topic: 'travel', level: 'A2', t: const Tr('fahren', 'to drive', 'köra', 'rijden')),
      LexemeSpec(id: 'lex_v_reisen', am: 'መጓዝ', tr: 'megwaz', pos: 'verb', topic: 'travel', level: 'A2', t: const Tr('reisen', 'to travel', 'resa', 'reizen')),
      LexemeSpec(id: 'lex_v_ankommen', am: 'መድረስ', tr: 'medres', pos: 'verb', topic: 'travel', level: 'A2', t: const Tr('ankommen', 'to arrive', 'anlända', 'aankomen')),
      LexemeSpec(id: 'lex_pass', am: 'ፓስፖርት', tr: 'pasport', pos: 'noun', topic: 'travel', level: 'A2', emoji: '📘', verified: true, t: const Tr('der Reisepass', 'passport', 'pass', 'paspoort')),
      LexemeSpec(id: 'lex_fahrrad', am: 'ብስክሌት', tr: 'bisiklet', pos: 'noun', topic: 'travel', level: 'A2', emoji: '🚲', verified: true, t: const Tr('das Fahrrad', 'bicycle', 'cykel', 'fiets')),
      LexemeSpec(id: 'lex_schiff', am: 'መርከብ', tr: 'merkeb', pos: 'noun', topic: 'travel', level: 'A2', emoji: '🚢', t: const Tr('das Schiff', 'ship', 'skepp', 'schip')),
      LexemeSpec(id: 'lex_karte', am: 'ካርታ', tr: 'karta', pos: 'noun', topic: 'travel', level: 'A2', emoji: '🗺️', verified: true, t: const Tr('die Landkarte', 'map', 'karta', 'kaart')),
      LexemeSpec(id: 'lex_hafen', am: 'ወደብ', tr: 'wedeb', pos: 'noun', topic: 'travel', level: 'A2', t: const Tr('der Hafen', 'port, harbor', 'hamn', 'haven')),
      LexemeSpec(id: 'lex_grenze', am: 'ድንበር', tr: 'dinber', pos: 'noun', topic: 'travel', level: 'A2', t: const Tr('die Grenze', 'border', 'gräns', 'grens')),
      LexemeSpec(id: 'lex_visum', am: 'ቪዛ', tr: 'visa', pos: 'noun', topic: 'travel', level: 'A2', verified: true, t: const Tr('das Visum', 'visa', 'visum', 'visum')),
      LexemeSpec(id: 'lex_tourist', am: 'ቱሪስት', tr: 'turist', pos: 'noun', topic: 'travel', level: 'A2', verified: true, t: const Tr('der Tourist', 'tourist', 'turist', 'toerist')),
      LexemeSpec(id: 'lex_bruecke', am: 'ድልድይ', tr: 'dildiy', pos: 'noun', topic: 'travel', level: 'A2', t: const Tr('die Brücke', 'bridge', 'bro', 'brug')),
    ],
    sentences: [
      SentenceSpec(id: 'sen_awroplan_megwaz', am: 'በአውሮፕላን እጓዛለሁ።', tr: 'be-awroplan igwazalehu.', level: 'A2', uses: ['lex_flugzeug', 'lex_v_reisen'], chunks: ['be-awroplan', 'igwazalehu'], t: const Tr('Ich reise mit dem Flugzeug.', 'I travel by airplane.', 'Jag reser med flygplan.', 'Ik reis met het vliegtuig.'), verified: false),
    ],
  ));

  writeUnit(UnitSpec(
    id: 'unit_wetter_natur',
    sectionId: 'sec_a2',
    level: 'A2',
    topic: 'weather_nature',
    title: const Tr('Wetter & Natur', 'Weather & nature', 'Väder & natur', 'Weer & natuur'),
    lexemes: [
      LexemeSpec(id: 'lex_sonne', am: 'ፀሐይ', tr: "ts'ehay", pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '☀️', verified: true, t: const Tr('die Sonne', 'sun', 'sol', 'zon')),
      LexemeSpec(id: 'lex_regen', am: 'ዝናብ', tr: 'zinab', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🌧️', verified: true, t: const Tr('der Regen', 'rain', 'regn', 'regen')),
      LexemeSpec(id: 'lex_wind', am: 'ነፋስ', tr: 'nefas', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '💨', verified: true, t: const Tr('der Wind', 'wind', 'vind', 'wind')),
      LexemeSpec(id: 'lex_berg', am: 'ተራራ', tr: 'terara', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '⛰️', verified: true, t: const Tr('der Berg', 'mountain', 'berg', 'berg')),
      LexemeSpec(id: 'lex_fluss', am: 'ወንዝ', tr: 'wenz', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🏞️', verified: true, t: const Tr('der Fluss', 'river', 'flod', 'rivier')),
      LexemeSpec(id: 'lex_baum', am: 'ዛፍ', tr: 'zaf', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🌳', verified: true, t: const Tr('der Baum', 'tree', 'träd', 'boom')),
      LexemeSpec(id: 'lex_tier', am: 'እንስሳ', tr: 'insisa', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🐾', verified: true, t: const Tr('das Tier', 'animal', 'djur', 'dier')),
      LexemeSpec(id: 'lex_hund', am: 'ውሻ', tr: 'wusha', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🐕', verified: true, t: const Tr('der Hund', 'dog', 'hund', 'hond')),
      LexemeSpec(id: 'lex_katze', am: 'ድመት', tr: 'dimet', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🐈', verified: true, t: const Tr('die Katze', 'cat', 'katt', 'kat')),
      LexemeSpec(id: 'lex_vogel', am: 'ወፍ', tr: 'wef', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🐦', verified: true, t: const Tr('der Vogel', 'bird', 'fågel', 'vogel')),
      LexemeSpec(id: 'lex_himmel', am: 'ሰማይ', tr: 'semay', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🌤️', verified: true, t: const Tr('der Himmel', 'sky', 'himmel', 'lucht')),
      LexemeSpec(id: 'lex_wolke', am: 'ደመና', tr: 'demena', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '☁️', verified: true, t: const Tr('die Wolke', 'cloud', 'moln', 'wolk')),
      LexemeSpec(id: 'lex_schnee', am: 'በረዶ', tr: 'beredo', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '❄️', t: const Tr('der Schnee, das Eis', 'snow, ice', 'snö, is', 'sneeuw, ijs')),
      LexemeSpec(id: 'lex_blume', am: 'አበባ', tr: 'abeba', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🌸', verified: true, t: const Tr('die Blume', 'flower', 'blomma', 'bloem')),
      LexemeSpec(id: 'lex_wetter', am: 'የአየር ሁኔታ', tr: "ye'ayer huneta", pos: 'noun', topic: 'weather_nature', level: 'A2', t: const Tr('das Wetter', 'weather', 'väder', 'weer')),
      LexemeSpec(id: 'lex_wald', am: 'ጫካ', tr: 'chaka', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🌲', t: const Tr('der Wald', 'forest', 'skog', 'bos')),
      LexemeSpec(id: 'lex_see', am: 'ሐይቅ', tr: 'hayk', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🏞️', t: const Tr('der See', 'lake', 'sjö', 'meer')),
      LexemeSpec(id: 'lex_meer', am: 'ውቅያኖስ', tr: "wik'yanos", pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🌊', t: const Tr('das Meer, der Ozean', 'sea, ocean', 'hav, ocean', 'zee, oceaan')),
      LexemeSpec(id: 'lex_stern', am: 'ኮከብ', tr: 'kokeb', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '⭐', t: const Tr('der Stern', 'star', 'stjärna', 'ster')),
      LexemeSpec(id: 'lex_mond', am: 'ጨረቃ', tr: "cherek'a", pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🌙', t: const Tr('der Mond', 'moon', 'måne', 'maan')),
      LexemeSpec(id: 'lex_feuer', am: 'እሳት', tr: 'isat', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🔥', t: const Tr('das Feuer', 'fire', 'eld', 'vuur')),
      LexemeSpec(id: 'lex_erde', am: 'መሬት', tr: 'meret', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🌍', t: const Tr('die Erde, der Boden', 'earth, ground', 'jord, mark', 'aarde, grond')),
      LexemeSpec(id: 'lex_luft', am: 'አየር', tr: 'ayer', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🌬️', verified: true, t: const Tr('die Luft', 'air', 'luft', 'lucht')),
      LexemeSpec(id: 'lex_loewe', am: 'አንበሳ', tr: 'anbesa', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🦁', verified: true, t: const Tr('der Löwe', 'lion', 'lejon', 'leeuw')),
      LexemeSpec(id: 'lex_elefant', am: 'ዝሆን', tr: 'zihon', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🐘', verified: true, t: const Tr('der Elefant', 'elephant', 'elefant', 'olifant')),
      LexemeSpec(id: 'lex_affe', am: 'ጦጣ', tr: "t'ot'a", pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🐒', t: const Tr('der Affe', 'monkey', 'apa', 'aap')),
      LexemeSpec(id: 'lex_schlange', am: 'እባብ', tr: 'ibab', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🐍', t: const Tr('die Schlange', 'snake', 'orm', 'slang')),
      LexemeSpec(id: 'lex_fisch', am: 'አሳ', tr: 'asa', pos: 'noun', topic: 'weather_nature', level: 'A2', emoji: '🐟', verified: true, t: const Tr('der Fisch', 'fish', 'fisk', 'vis')),
    ],
    sentences: [
      SentenceSpec(id: 'sen_zare_tsehay', am: 'ዛሬ ፀሐይ አለ።', tr: "zare ts'ehay ale.", level: 'A2', uses: ['lex_heute', 'lex_sonne'], chunks: ['zare', "ts'ehay", 'ale'], t: const Tr('Heute ist Sonne.', "Today it's sunny.", 'Idag är det soligt.', 'Vandaag is het zonnig.'), verified: false),
      SentenceSpec(id: 'sen_wushaw_konjo', am: 'ውሻው ቆንጆ ነው።', tr: 'wushaw konjo new.', level: 'A2', uses: ['lex_hund', 'lex_schoen'], chunks: ['wushaw', 'konjo', 'new'], t: const Tr('Der Hund ist schön.', 'The dog is nice.', 'Hunden är fin.', 'De hond is mooi.')),
    ],
  ));
}
